### ISSUE TITLE
max_eval counter doesn't reset

### ISSUE THREAD

**Issue by metelkin** [JuliaSmoothOptimizers/DerivativeFreeSolvers.jl#14]
Thank you for your work! I am interested in derivative-free optimizers.

I played with methods and it seems the `max_eval` stop criterion not working as expected in all three methods.
If you run the optimization two or more times with `max_eval = 10` (as an example) the internal counter will not reset and may stop without optimization
This is because the code uses `neval_obj(nlp)` function and the internal nlp counter which is a mutable value.

It requires a trivial fix but before pulling a request I wonder if it is a bug or a feature.

**Comment by dpo** [comment]
Call `reset!(nlp)` before calling the solver a second time.

**Comment by metelkin** [comment]
> Call `reset!(nlp)` before calling the solver a second time.

Thank you. 
It is still unclear if it is a workaround or a proper way. If so I should reset each time when I repeat the optimization with `max_eval`. But I have not to do `reset!` if I use `max_iter`, `max_time`, etc. It's confusing a little bit.

**Comment by dpo** [comment]
Yes, that's the intended way. The evaluation counter is stored in the `nlp`, and calling the solver only increases it. So you can either reset the counter, or increase `max_iter` to account for the additional number of iteration you want to allow.

**Comment by metelkin** [comment]
Ok. Thanks.
